feat: update snapd to 2.60.2-1

diff --git a/run-checks b/run-checks
--- a/run-checks
+++ b/run-checks
@@ -1,4 +1,4 @@
-#!/bin/sh -eu
+#!/bin/bash -eu
 
 export LANG=C.UTF-8
 export LANGUAGE=en
@@ -9,10 +9,13 @@ else
     goctest="go test"
 fi
 COVERMODE=${COVERMODE:-atomic}
+COVERAGE_SUFFIX=${GO_BUILD_TAGS:-notags}
+COVERAGE_OUT=${COVERAGE_OUT:-.coverage/coverage-$COVERAGE_SUFFIX.cov}
+CHANGED_FILES=${CHANGED_FILES:-""}
 
 if [ -z "${GITHUB_WORKFLOW:-}" ]; then
-    # when *not* running inside github, ensure we use go-1.10 by default
-    export PATH=/usr/lib/go-1.10/bin:"${PATH}"
+    # when *not* running inside github, ensure we use go-1.18 by default
+    export PATH=/usr/lib/go-1.18/bin:"${PATH}"
 fi
 
 # add workaround for https://github.com/golang/go/issues/24449
@@ -24,8 +27,13 @@ if [ "$(uname -m)" = "s390x" ]; then
     fi
 fi
 
-export GOPATH="${GOPATH:-$(realpath "$(dirname "$0")"/../../../../)}"
-export PATH="$PATH:${GOPATH%%:*}/bin"
+# If GOPATH is set in the shell environment, the path will be reflected
+# in $(go env GOPATH). If no shell path was set, Go will default the internal
+# GOPATH to $HOME/go. Note that GOPATH may contain a colon delimited set
+# of paths, so in order to run any binary from any of the installed GOPATHs
+# we must add all the possible bin locations.
+GOBINS=$(go env GOPATH | sed 's|:|/bin:|g' | sed 's|.*|\0/bin|g')
+export PATH="$PATH:$GOBINS"
 
 short=
 
@@ -48,7 +56,7 @@ case "${1:-all}" in
         short=1
         ;;
     *)
-        echo "Wrong flag ${1}. To run a single suite use --static, --unit, --spread."
+        echo "Wrong flag ${1}. To run a single suite use --static, --unit."
         exit 1
 esac
 
@@ -69,6 +77,20 @@ addtrap() {
     trap "store_exit_code; $CURRENTTRAP ; exit_with_exit_code" EXIT
 }
 
+goinstall() {
+    pkg="$1"
+    version="${2:-}"
+    # go1.18+ will no longer build/install packages. Here "go install"
+    # must be used but it will only fetch remote packages if the @latest
+    # (or similar syntax is used). Instead of checking the version we
+    # check if the "go install" help mentions this new feature.
+    if go help install | grep -q @latest; then
+        go install "${pkg}"@"${version:=latest}"
+    else
+        go get -u "${pkg}"@"${version:=latest}"
+    fi
+}
+
 endmsg() {
     if [ $EXIT_CODE -eq 0 ]; then
         p="success.txt"
@@ -86,19 +108,10 @@ endmsg() {
 }
 addtrap endmsg
 
-# Append the coverage profile of a package to the project coverage.
-append_coverage() (
-    profile="$1"
-    if [ -f "$profile" ]; then
-        grep -v "^mode:" -- "$profile" >> .coverage/coverage.out || true
-        rm "$profile"
-    fi
-)
-
 missing_interface_spread_test() {
     snap_yaml="tests/lib/snaps/test-snapd-policy-app-consumer/meta/snap.yaml"
-    core_snap_yaml="tests/lib/snaps/test-snapd-policy-app-provider-core/meta/snap.yaml"
-    classic_snap_yaml="tests/lib/snaps/test-snapd-policy-app-provider-classic/meta/snap.yaml"
+    core_snap_yaml="tests/main/interfaces-many-snap-provided/test-snapd-policy-app-provider-core/meta/snap.yaml"
+    classic_snap_yaml="tests/main/interfaces-many-snap-provided/test-snapd-policy-app-provider-classic/meta/snap.yaml"
     for iface in $(go run ./tests/lib/list-interfaces.go) ; do
         search="plugs: \\[ $iface \\]"
         case "$iface" in
@@ -129,22 +142,24 @@ if [ "$STATIC" = 1 ]; then
 
     # Run static tests.
     echo Checking docs
-    ./mdlint.py ./*.md docs/*.md
+    ./mdlint.py ./*.md ./**/*.md
 
     # XXX: remove once we can use an action, see workflows/test.yaml for
     #      details why we still use this script
-    if [ -n "${TRAVIS_PULL_REQUEST:-}" ] && [ "${TRAVIS_PULL_REQUEST:-}" != "false" ]; then
+    if [ -n "${GITHUB_PULL_REQUEST:-}" ] && [ "${GITHUB_PULL_REQUEST:-}" != "false" ]; then
         echo Checking pull request summary
-        ./check-pr-title.py "$TRAVIS_PULL_REQUEST"
+        ./check-pr-title.py "$GITHUB_PULL_REQUEST"
     fi
+
+    # check commit author/committer name for unicode
+    ./check-commit-email.py
 
     if [ -z "${SKIP_GOFMT:-}" ]; then
         echo Checking formatting
         fmt=""
-        for dir in $(go list -f '{{.Dir}}' ./... | grep -v '/vendor/' | grep -E 'snapd/[A-Za-z0-9_]+$' ); do
+        for dir in $(go list -f '{{.Dir}}' ./... | grep -v '/\(c-\)\?vendor/' ); do
             # skip vendor packages
-            # skip subpackages of packages under snapd, gofmt already inspects them
-            s="$(${GOFMT:-gofmt} -s -l -d "$dir" || true)"
+            s="$(${GOFMT:-gofmt} -s -d "$dir" || true)"
             if [ -n "$s" ]; then
                 fmt="$s\\n$fmt"
             fi
@@ -193,12 +208,33 @@ if [ "$STATIC" = 1 ]; then
     fi
 
     if command -v shellcheck >/dev/null; then
-        echo Checking shell scripts...
-        ( git ls-files -z 2>/dev/null ||
-                find . \( -name .git -o -name vendor \) -prune -o -print0 ) |
-            xargs -0 file -N |
-            awk -F": " '$2~/shell.script/{print $1}' |
-            xargs shellcheck -x
+        exclude_tools_path=tests/lib/external/snapd-testing-tools
+        echo "Checking shell scripts..."
+        if [ -n "$CHANGED_FILES" ]; then
+            echo "Checking just the changed bash files"
+            echo "Changed files: $CHANGED_FILES"
+            # shellcheck disable=SC2086
+            INITIAL_FILES="$( file -N $CHANGED_FILES | awk -F": " '$2~/shell.script/{print $1}' )"
+        else
+            echo "Checking all the bash files"
+            INITIAL_FILES="$( ( git ls-files -z 2>/dev/null || find . \( -name .git -o -name vendor -o -name c-vendor \) -prune -o -print0) | xargs -0 file -N | awk -F": " '$2~/shell.script/{print $1}' )"
+        fi
+
+        echo "Filtering files"
+        FILTERED_FILES=
+        for file in $INITIAL_FILES; do
+            if ! echo "$file" | grep -q "$exclude_tools_path"; then
+                FILTERED_FILES="$FILTERED_FILES $file"
+            fi
+        done
+        if [ -n "$FILTERED_FILES" ]; then
+            echo "Running shellcheck for files: $FILTERED_FILES"
+            # shellcheck disable=SC2086
+            shellcheck -x $FILTERED_FILES
+        else
+            echo "Skipping shellcheck, no files to check"
+        fi
+
         regexp='GOPATH(?!%%:\*)(?!:)[^= ]*/'
         if  grep -qPr                   --exclude HACKING.md --exclude 'Makefile.*' --exclude-dir .git --exclude-dir vendor "$regexp"; then
             echo "Using GOPATH as if it were a single entry and not a list:"
@@ -207,33 +243,52 @@ if [ "$STATIC" = 1 ]; then
             exit 1
         fi
         unset regexp
+
         # also run spread-shellcheck
-        ./spread-shellcheck spread.yaml tests
-    fi
-
-    echo "Checking spelling errors"
-    if ! command -v misspell >/dev/null; then
-        go get -u github.com/client9/misspell/cmd/misspell
-    fi
-    # FIXME: auter is only misspelled in the changelog so we should fix there
-    # PROCES is used in the seccomp tests (PRIO_PROCES{,S,SS})
-    # exportfs is used in the nfs-support test
-    MISSPELL_IGNORE="auther,PROCES,PROCESSS,proces,processs,exportfs"
-    git ls-files -z -- . ':!:./po' ':!:./vendor' |
-        xargs -0 misspell -error -i "$MISSPELL_IGNORE"
-
-    if dpkg --compare-versions "$(go version | awk '$3 ~ /^go[0-9]/ {print substr($3, 3)}')" ge 1.12; then
-        echo "Checking for ineffective assignments"
-        if ! command -v ineffassign >/dev/null; then
-            go get -u github.com/gordonklaus/ineffassign
+        FILTERED_FILES="spread.yaml"
+        if [ -n "$CHANGED_FILES" ]; then
+            # shellcheck disable=SC2086
+            for changed_file in $CHANGED_FILES; do
+                if [[ $changed_file == */task.yaml ]]; then
+                    FILTERED_FILES="$FILTERED_FILES $changed_file"
+                fi
+            done
+        else
+            FILTERED_FILES="$FILTERED_FILES tests"
         fi
-        # ineffassign knows about ignoring vendor/ \o/
-        ineffassign ./...
+        # XXX: exclude core20-preseed test as its environment block confuses shellcheck, and it's not possible to disable shellcheck there.
+        # shellcheck disable=SC2086
+        ./tests/lib/external/snapd-testing-tools/utils/spread-shellcheck $FILTERED_FILES --exclude "$exclude_tools_path" --exclude "tests/nested/manual/core20-preseed"
+    fi
+
+    if [ -z "${SKIP_MISSPELL-}" ]; then
+        echo "Checking spelling errors"
+        if ! command -v misspell >/dev/null; then
+            goinstall github.com/client9/misspell/cmd/misspell
+        fi
+        # FIXME: auter is only misspelled in the changelog so we should fix there
+        # PROCES is used in the seccomp tests (PRIO_PROCES{,S,SS})
+        # exportfs is used in the nfs-support test
+        # becuase because of misspell in upstream steam rules (PR#12657)
+        MISSPELL_IGNORE="auther,PROCES,PROCESSS,proces,processs,exportfs,becuase"
+        git ls-files -z -- . ':!:./po' ':!:./vendor' ':!:./c-vendor' ':!:./cmd/libsnap-confine-private/bpf/vendor' |
+            xargs -0 misspell -error -i "$MISSPELL_IGNORE"
+    fi
+
+    if [ -z "${SKIP_INEFFASSIGN-}" ]; then
+        if dpkg --compare-versions "$(go version | awk '$3 ~ /^go[0-9]/ {print substr($3, 3)}')" ge 1.12; then
+            echo "Checking for ineffective assignments"
+            if ! command -v ineffassign >/dev/null; then
+                goinstall github.com/gordonklaus/ineffassign
+            fi
+            # ineffassign knows about ignoring vendor/ \o/
+            ineffassign ./...
+        fi
     fi
 
     echo "Checking for naked returns"
     if ! command -v nakedret >/dev/null; then
-        go get -u github.com/alexkohler/nakedret
+        goinstall github.com/alexkohler/nakedret v1.0.1
     fi
     got=$(go list ./... | grep -v '/osutil/udev/' | grep -v '/vendor/' | xargs nakedret 2>&1)
     if [ -n "$got" ]; then
@@ -267,6 +322,18 @@ if [ "$STATIC" = 1 ]; then
     fi
 
     # FIXME: re-add staticcheck with a matching version for the used go-version
+
+    if [ -z "${SKIP_TESTS_FORMAT_CHECK-}" ] || [ "$SKIP_TESTS_FORMAT_CHECK" = 0 ]; then
+        echo "Checking tests formatting"
+        ./tests/lib/external/snapd-testing-tools/utils/check-test-format ./tests
+    fi
+
+    echo "Checking for usages of !=, == or Equals with ErrNoState"
+    if got=$(grep -n -R -E "(\!=|==|Equals,) (state\.)?ErrNoState" --include=*.go) ; then
+      echo "Don't use equality checks with ErrNoState, use errors.Is() instead"
+      echo "$got"
+      exit 1
+    fi
 fi
 
 if [ "$UNIT" = 1 ]; then
@@ -294,29 +361,16 @@ if [ "$UNIT" = 1 ]; then
     else
         coverage=""
         if [ -z "${SKIP_COVERAGE-}" ]; then
-            coverage="-coverprofile=.coverage/coverage.out -covermode=$COVERMODE"
+            coverage="-coverprofile=$COVERAGE_OUT -covermode=$COVERMODE"
             # Prepare the coverage output profile.
-            rm -rf .coverage
-            mkdir .coverage
-            echo "mode: $COVERMODE" > .coverage/coverage.out
+            mkdir -p "$(dirname "$COVERAGE_OUT")"
+            echo "mode: $COVERMODE" > "$COVERAGE_OUT"
         else
             echo "Skipping test coverage"
         fi
 
-        if command -v dpkg >/dev/null && dpkg --compare-versions "$(go version | awk '$3 ~ /^go[0-9]/ {print substr($3, 3)}')" ge 1.10; then
-            # shellcheck disable=SC2046,SC2086
-            GOTRACEBACK=1 $goctest $tags -timeout 5m $coverage $(go list ./... | grep -v '/vendor/' )
-        else
-            for pkg in $(go list ./... | grep -v '/vendor/' ); do
-                # shellcheck disable=SC2086
-                GOTRACEBACK=1 go test $tags -timeout 5m -i "$pkg"
-                if [ -z "${SKIP_COVERAGE-}" ]; then
-                    # shellcheck disable=SC2086
-                    GOTRACEBACK=1 $goctest $tags -timeout 5m $coverage "$pkg"
-                    append_coverage .coverage/profile.out
-                fi
-            done
-        fi
+        # shellcheck disable=SC2046,SC2086
+        GOTRACEBACK=1 $goctest $tags -timeout 5m $coverage $(go list ./... | grep -v '/vendor/' )
     fi
 
     # python unit test for mountinfo.query and version-compare
@@ -342,8 +396,9 @@ if [ -n "${SKIP_DIRTY_CHECK-}" ]; then
     exit 0
 fi
 
-if git describe --always --dirty | grep -q dirty; then
-    echo "Build tree is dirty"
-    git diff
-    exit 1
-fi
+# XXX: re-enable after vendor/vendor.json is removed
+# if git describe --always --dirty | grep -q dirty; then
+#     echo "Build tree is dirty"
+#     git diff
+#     exit 1
+# fi
diff --git a/tests/main/snapshot-basic/task.yaml b/tests/main/snapshot-basic/task.yaml
--- a/tests/main/snapshot-basic/task.yaml
+++ b/tests/main/snapshot-basic/task.yaml
@@ -1,5 +1,9 @@
 summary: Check that the basic snapshots functionality is ok
 
+environment:
+    # tar invoked when creating snapshots triggers OOM
+    SNAPD_NO_MEMORY_LIMIT: 1
+
 prepare: |
     snap install test-snapd-sh
     snap install --edge test-snapd-just-edge
@@ -72,6 +76,21 @@ execute: |
     snap forget "$SET_ID"
     snap saved --id="$SET_ID" | grep "No snapshots found"
 
+    echo "Check import fails if snapshot contains invalid filenames"
+    # trusty (14.04) relpath does not support --relative-to
+    if ! os.query is-trusty; then
+        fname=$(mktemp /tmp/1_XXXX)
+        relpath=$(realpath  --relative-to="$(pwd)" "$fname")
+        cp "${SET_ID}_export.snapshot" "${SET_ID}_export.snapshot.invalid"
+        tar --update -f "${SET_ID}_export.snapshot.invalid" -P "$relpath"
+        # remove the file so we can check that the file does not get created when
+        # snapshot import fails
+        rm "$fname"
+        snap import-snapshot "${SET_ID}_export.snapshot.invalid" && exit 1
+        test ! -e "$fname"
+        rm "${SET_ID}_export.snapshot.invalid"
+    fi
+
     echo "Check that import works"
     RESTORE_ID=$( snap import-snapshot "${SET_ID}_export.snapshot" | head -n1 | cut -f2 -d'#' )
     echo "And is valid"
@@ -86,7 +105,7 @@ execute: |
 
     snap forget "$RESTORE_ID"
     echo "Import re-creates snapshots directory if misssing"
-    # sanity check
+    # precondition check
     test -d /var/lib/snapd/snapshots
     rm -rf /var/lib/snapd/snapshots
     RESTORE_ID=$( snap import-snapshot "${SET_ID}_export.snapshot" | head -n1 | cut -f2 -d'#' )
