feat: update snapd to 2.65.1-1

diff --git a/tests/nested/manual/core20-install-mode-shutdown-via-hook/task.yaml b/tests/nested/manual/core20-install-mode-shutdown-via-hook/task.yaml
--- a/tests/nested/manual/core20-install-mode-shutdown-via-hook/task.yaml
+++ b/tests/nested/manual/core20-install-mode-shutdown-via-hook/task.yaml
@@ -4,7 +4,7 @@ details: |
     This test checks support for shutting down the device at the end of install
     mode via the install-device hook
 
-systems: [ubuntu-20.04-64, ubuntu-22.04-64]
+systems: [ubuntu-2*]
 
 environment:
     NESTED_BUILD_SNAPD_FROM_CURRENT: true
@@ -41,8 +41,6 @@ restore: |
     tests.cleanup restore
 
 execute: |
-    #shellcheck source=tests/lib/systemd.sh
-    . "$TESTSLIB/systemd.sh"
     #shellcheck source=tests/lib/nested.sh
     . "$TESTSLIB/nested.sh"
 
@@ -62,7 +60,7 @@ execute: |
     NESTED_EXPECT_SHUTDOWN=1 nested_start_core_vm_unit "$IMAGE_FILE"
 
     echo "Wait for the VM to become inactive as it installs and shuts itself down"
-    wait_for_service "$NESTED_VM" inactive 180
+    tests.systemd wait-for-service -n 180 --state inactive "$NESTED_VM"
 
     echo "Check that the partitions were created on the VM's disk"
     sfdisk --json "$IMAGE_FILE" | jq -r '.partitiontable.partitions | .[].name' > partitions.txt
@@ -89,7 +87,12 @@ execute: |
     # Wait for snap seeding to be done
     remote.exec "sudo snap wait system seed.loaded"
     # Wait for cloud init to be done
-    remote.exec "cloud-init status --wait"
+    ret=0
+    remote.exec "cloud-init status --wait" || ret=$?
+    if [ "$ret" -ne 0 ] && [ "$ret" -ne 2 ]; then
+        echo "cloud-init finished with error $ret"
+        exit 1
+    fi
 
     echo "The device is using encrypted ubuntu-data and is in run mode now"
     remote.exec test -L /dev/disk/by-label/ubuntu-data-enc
