feat: update snapd to 2.60.2-1

diff --git a/tests/main/interfaces-network-control/task.yaml b/tests/main/interfaces-network-control/task.yaml
--- a/tests/main/interfaces-network-control/task.yaml
+++ b/tests/main/interfaces-network-control/task.yaml
@@ -1,8 +1,5 @@
 summary: Ensure that the network-control interface works.
 
-# ubuntu-14.04: systemd-run not supported
-systems: [-fedora-*, -opensuse-*, -ubuntu-14.04*]
-
 details: |
     The network-control interface allows a snap to configure networking.
 
@@ -13,6 +10,12 @@ details: |
     A snap declaring a plug on this interface must be able to modify the network configuration
     and ask for its status, the test sets up a network service, gets information about it (read
     capability) and creates an arp entry (write capability).
+
+# ubuntu-14.04: systemd-run not supported
+# ubuntu-18.04-32: network-control-consumer snap not available on i386
+# ubuntu-core-16-32: cannot install snap base "core20"
+# ubuntu-core-18-32: cannot install snap base "core20"
+systems: [-fedora-*, -opensuse-*, -ubuntu-14.04*, -ubuntu-18.04-32, -ubuntu-core-16-32, -ubuntu-core-18-32]
 
 environment:
     PORT: 8081
@@ -53,6 +56,16 @@ execute: |
 
     echo "Then the snap command can query network status information"
     network-control-consumer.cmd ss -lnt | MATCH "LISTEN.*:$PORT"
+
+    echo "And DNS information"
+    case "$SPREAD_SYSTEM" in
+    centos-*|debian-*|arch-linux-*|amazon-linux-*)
+        # echo no systemd-resolved in those images
+        ;;
+    *)
+        network-control-consumer.cmd resolvectl | MATCH "DNS Server"
+        ;;
+    esac
 
     if [ "$(snap debug confinement)" = strict ] ; then
         echo "When the plug is disconnected"
@@ -103,10 +116,16 @@ execute: |
     network-control-consumer.cmd ip link set veth1 netns test-ns
 
     ip link list | MATCH "veth0"
-    ip link list | not MATCH "veth1"
+    ip link list | NOMATCH "veth1"
 
     echo "And a command can be executed in the context of the namespace"
     network-control-consumer.cmd ip netns exec test-ns ip link list | MATCH "veth1"
+
+    # xdp is only support by apparmor in 20.04+
+    if [ "$(snap debug confinement)" = strict ] && ! os.query is-xenial && ! os.query is-bionic && ! os.query is-core16 && ! os.query is-core18; then
+        echo "Check that AF_XDP can be used"
+        network-control-consumer.cmd python3 -c 'import socket; AF_XDP=44; socket.socket(AF_XDP, socket.SOCK_RAW)'
+    fi
 
     if [ "$(snap debug confinement)" = strict ] ; then
         echo "And the policy has the ptrace suppression rule"
@@ -137,4 +156,14 @@ execute: |
             exit 1
         fi
         MATCH "Permission denied" < ns-exec.output
+
+
+        echo "And AF_XDP can no longer be used"
+        if [ "$(snap debug confinement)" = strict ] && ! os.query is-xenial && ! os.query is-bionic && ! os.query is-core16 && ! os.query is-core18; then
+            if network-control-consumer.cmd python3 -c 'import socket; AF_XDP=44; socket.socket(AF_XDP, socket.SOCK_RAW)' 2> python-af-xdp.output; then
+                echo "Expected error trying to open AF_XDP socket"
+                exit 1
+            fi
+            MATCH "Permission denied" < python-af-xdp.output
+        fi
     fi
diff --git a/tests/main/preseed-lxd/task.yaml b/tests/main/preseed-lxd/task.yaml
--- a/tests/main/preseed-lxd/task.yaml
+++ b/tests/main/preseed-lxd/task.yaml
@@ -5,38 +5,39 @@ details: |
   command works in lxc container and that the resulting image can be run
   in a container and seeding finishes successfully.
 
-# this test works only on 18.04 because it requires lxd from deb (lxd snap
+# this test works only on 18.04-64 because it requires lxd from deb (lxd snap
 # as it wouldn't allow mount) and tries to replicate launchpad builder setup.
-systems: [ubuntu-18.04-*]
+systems: [ubuntu-18.04-64]
 
 environment:
   IMAGE_MOUNTPOINT: /mnt/cloudimg
 
 prepare: |
-  #shellcheck source=tests/lib/nested.sh
-  . "$TESTSLIB/nested.sh"
-
-  #shellcheck source=tests/lib/snaps.sh
-  . "$TESTSLIB/snaps.sh"
-
   #shellcheck source=tests/lib/preseed.sh
   . "$TESTSLIB/preseed.sh"
 
-  IMGURL=$(nested_get_image_url_for_vm ubuntu-20.04-64)
-  wget --quiet "$IMGURL" -O cloudimg.img
+  # shellcheck source=tests/lib/image.sh
+  . "$TESTSLIB"/image.sh
+  wget --quiet "$(get_image_url_for_vm ubuntu-20.04-64)" -O cloudimg.img
 
   modprobe nbd
 
   # Run qemu-nbd as a service, so that it does not interact with ssh
   # stdin/stdout it would otherwise inherit from the spread session.
-  systemd-run --system --service-type=forking --unit=qemu-nbd-preseed.service "$(command -v qemu-nbd)" --fork -c /dev/nbd0 "$(pwd)/cloudimg.img"
+  # TODO: re-use tests/lib/preseed.sh:mount_ubuntu_image() here
+  systemd-run --system --service-type=forking --unit=qemu-nbd-preseed.service "$(command -v qemu-nbd)" -v --fork -c /dev/nbd0 "$(pwd)/cloudimg.img"
   # nbd0p1 may take a short while to become available
-  retry -n 5 --wait 1 test -e /dev/nbd0p1
+  if ! retry -n 30 --wait 1 test -e /dev/nbd0p1; then
+        echo "ERROR: /dev/nbd0p1 did not show up"
+        journalctl -u qemu-nbd-preseed.service
+        find /dev/ -name "nbd0*" -ls
+        exit 1
+  fi
   mkdir -p "$IMAGE_MOUNTPOINT"
   mount /dev/nbd0p1 "$IMAGE_MOUNTPOINT"
 
   # add snapd from this branch into the seed
-  repack_snapd_deb_into_snapd_snap "$PWD"
+  "$TESTSTOOLS"/snaps-state repack_snapd_deb_into_snap snapd
   mv snapd-from-deb.snap snapd.snap
   inject_snap_into_seed "$IMAGE_MOUNTPOINT" snapd
 
@@ -64,7 +65,7 @@ restore: |
 
   # qemu-nbd -d may sporadically fail when removing the device,
   # reporting it's still in use.
-  retry -n 5 --wait 1 qemu-nbd -d /dev/nbd0
+  retry -n 30 --wait 1 qemu-nbd -d /dev/nbd0
 
   "$TESTSTOOLS"/lxd-state undo-mount-changes
 
@@ -103,12 +104,12 @@ execute: |
   lxc exec my-ubuntu -- "$GOHOME"/preseed-prepare.sh "$IMAGE_MOUNTPOINT"
   lxc exec my-ubuntu -- "$GOHOME"/snap-preseed "$IMAGE_MOUNTPOINT"
 
-  echo "Sanity check of mount units"
+  echo "Precondition check of mount units"
   # preseeded image is mounted on the host, so we can directly inspect
   # preseeding artifacts.
   MATCH "Type=squashfs$" < "$IMAGE_MOUNTPOINT"/etc/systemd/system/snap-lxd-*.mount
   MATCH "Type=squashfs$" < "$IMAGE_MOUNTPOINT"/etc/systemd/system/snap-snapd-*.mount
-  MATCH "Type=squashfs$" < "$IMAGE_MOUNTPOINT"/etc/systemd/system/snap-core18-*.mount
+  MATCH "Type=squashfs$" < "$IMAGE_MOUNTPOINT"/etc/systemd/system/snap-core20-*.mount
 
   snap debug state "$IMAGE_MOUNTPOINT"/var/lib/snapd/state.json --change=1 > tasks.log
 
@@ -145,8 +146,8 @@ execute: |
     exit 1
   fi
 
-  echo "Sanity check that mount overrides were generated inside the container"
+  echo "Precondition check that mount overrides were generated inside the container"
   lxc exec my-ubuntu-preseeded -- find /var/run/systemd/generator/ -name container.conf > overrides.log
-  MATCH "/var/run/systemd/generator/snap-core18.*mount.d/container.conf" < overrides.log
+  MATCH "/var/run/systemd/generator/snap-core20.*mount.d/container.conf" < overrides.log
   MATCH "/var/run/systemd/generator/snap-snapd-.*mount.d/container.conf" < overrides.log
   MATCH "/var/run/systemd/generator/snap-lxd-.*mount.d/container.conf" < overrides.log
